# Importing all the required libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

#Importing nacc file

In [2]:
nacc = pd.read_csv("/content/drive/MyDrive/HSOC_Alzheimer's_project/investigator_nacc69.csv")

/tmp/ipython-input-208485032.py:1: DtypeWarning: Columns (20,22,24,26,28,41,44,46,48,51,61,63,65,67,69,71,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,134,156,165,176,179,189,217,220,222,224,226,228,230,232,234,236,238,240,242,244,246,248,250,252,254,256,258,260,262,264,266,268,270,272,382,397,399,401,419,421,423,432,445,454,494,574,605,613,638,674,690,704,707,710,715,727,738,744,746,804,809,810,811,812,820,831,833,835,837,843,904,959,960,961,969,970,971,972,982,1004,1007,1010) have mixed types. Specify dtype option on import or set low_memory=False.
  nacc = pd.read_csv("/content/drive/MyDrive/HSOC_Alzheimer's_project/investigator_nacc69.csv")

#Basic Quality Checks

In [3]:
nacc.head()

,NACCID,NACCADC,PACKET,FORMVER,VISITMO,VISITDAY,VISITYR,NACCVNUM,NACCAVST,NACCNVST,...,NPATGAM1,NPATGAM2,NPATGAM3,NPATGAM4,NPATGAM5,NPATGFRN,NPATGFR1,NPATGFR2,NPATGFR3,NPATGFR4
0,NACC002909,186,I,3.0,12,28,2022,1,2,2,...,-4,-4,-4,-4,-4,-4,-4,-4,-4,-4
1,NACC002909,186,F,3.0,1,23,2024,2,2,2,...,-4,-4,-4,-4,-4,-4,-4,-4,-4,-4
2,NACC003487,186,I,3.0,11,15,2023,1,1,1,...,-4,-4,-4,-4,-4,-4,-4,-4,-4,-4
3,NACC004352,186,I,3.0,10,5,2021,1,1,1,...,-4,-4,-4,-4,-4,-4,-4,-4,-4,-4
4,NACC004687,186,I,3.0,11,14,2022,1,2,2,...,-4,-4,-4,-4,-4,-4,-4,-4,-4,-4

In [4]:
nacc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201352 entries, 0 to 201351
Columns: 1024 entries, NACCID to NPATGFR4
dtypes: float64(143), int64(739), object(142)
memory usage: 1.5+ GB

In [5]:
nacc.describe()

,NACCADC,FORMVER,VISITMO,VISITDAY,VISITYR,NACCVNUM,NACCAVST,NACCNVST,NACCDAYS,NACCFDYS,...,NPATGAM1,NPATGAM2,NPATGAM3,NPATGAM4,NPATGAM5,NPATGFRN,NPATGFR1,NPATGFR2,NPATGFR3,NPATGFR4
count,201352.000000,201352.000000,201352.000000,201352.000000,201352.000000,201352.000000,201352.000000,201352.000000,201352.000000,201352.000000,...,201352.000000,201352.000000,201352.000000,201352.000000,201352.000000,201352.000000,201352.000000,201352.000000,201352.000000,201352.000000
mean,4987.293412,2.376063,6.393713,15.435998,2014.657778,3.851946,6.703892,5.824089,2468.306453,1219.594675,...,-3.903805,-3.901709,-3.906403,-3.902206,-3.905186,-3.883825,-3.965419,-3.963899,-3.965016,-3.966194
std,2987.347193,0.696965,3.388243,8.609174,5.491822,3.147028,4.327328,4.016413,1816.010436,1327.853096,...,0.790323,0.820071,0.781629,0.809371,0.783408,0.863019,0.484034,0.497615,0.483989,0.479284
min,186.000000,1.000000,1.000000,1.000000,2005.000000,1.000000,1.000000,1.000000,0.000000,0.000000,...,-4.000000,-4.000000,-4.000000,-4.000000,-4.000000,-4.000000,-4.000000,-4.000000,-4.000000,-4.000000
25%,2289.000000,2.000000,3.000000,8.000000,2010.000000,1.000000,3.000000,3.000000,1014.000000,0.000000,...,-4.000000,-4.000000,-4.000000,-4.000000,-4.000000,-4.000000,-4.000000,-4.000000,-4.000000,-4.000000
50%,4967.000000,2.000000,6.000000,15.000000,2014.000000,3.000000,6.000000,5.000000,2177.000000,784.000000,...,-4.000000,-4.000000,-4.000000,-4.000000,-4.000000,-4.000000,-4.000000,-4.000000,-4.000000,-4.000000
75%,8361.000000,3.000000,9.000000,23.000000,2019.000000,5.000000,10.000000,8.000000,3711.000000,1855.000000,...,-4.000000,-4.000000,-4.000000,-4.000000,-4.000000,-4.000000,-4.000000,-4.000000,-4.000000,-4.000000
max,9661.000000,3.200000,12.000000,31.000000,2025.000000,20.000000,20.000000,20.000000,7020.000000,7020.000000,...,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000

#Creating copy of original file. all changes/modifications will executed on this file.

In [6]:
nacc_copy = nacc.copy()

Copies created:
- nacc_copy: 201352 rows

# **Cleaning the nacc_copy file**

#Selecting only required columns

In [8]:
# Important columns to always keep
important_columns = [
    'NACCID', 'visit_date', 'Age', 'SEX', 'EDUC', 'NACCNE4S', 'NACCFAM',
    'NACCGDS', 'DEP2YRS', 'NACCMMSE', 'CRAFTVRS', 'CRAFTDVR',
    'DIGFORCT', 'DIGBACCT', 'NACCUDSD', 'ANIMALS', 'TRAILA',
    'TRAILB', 'NACCALZD'
]

# Config thresholds
missing_threshold = 0.9    # Drop columns with >90% missing values
correlation_threshold = 0.95

df = nacc_copy  # Using reference (faster than .copy())

# Ensure all important columns exist in dataset
important_columns = [col for col in important_columns if col in df.columns]

# Separate important columns
df_important = df[important_columns]

# Step 1: Keep only numeric columns from the rest
df_numeric = df.select_dtypes(include=[np.number])

# Step 2: Drop columns with only one unique value
df_numeric = df_numeric.loc[:, df_numeric.nunique() > 1]

# Step 3: Drop high-missing-value columns
df_numeric = df_numeric.dropna(thresh=(1 - missing_threshold) * len(df_numeric), axis=1)

# Step 4: Fill missing values with median
df_numeric = df_numeric.fillna(df_numeric.median(numeric_only=True))

# Step 5 (Optimized): Remove duplicate columns WITHOUT transpose
# We use a hash of the column values instead of df.T
col_hashes = df_numeric.apply(lambda x: pd.util.hash_pandas_object(x, index=False).sum())
df_numeric = df_numeric.loc[:, ~col_hashes.duplicated()]

# Step 6 (Optimized): Remove highly correlated columns without full N×N matrix
# We'll iterate through columns and drop as soon as we find high correlation
corr_matrix = df_numeric.corr().abs()
cols_to_drop = set()
for i, col in enumerate(corr_matrix.columns):
    if col not in cols_to_drop:
        high_corr = corr_matrix.index[(corr_matrix[col] > correlation_threshold) & (corr_matrix.index != col)]
        cols_to_drop.update(high_corr)
df_numeric = df_numeric.drop(columns=list(cols_to_drop), errors='ignore')

# Merge back important columns (avoiding duplicates)
final_df = pd.concat(
    [df_important, df_numeric.drop(columns=[c for c in df_numeric.columns if c in df_important], errors='ignore')],
    axis=1
)

nacc_copy = final_df.copy()

In [9]:
nacc_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201352 entries, 0 to 201351
Columns: 406 entries, NACCID to NPATGFR1
dtypes: float64(35), int64(370), object(1)
memory usage: 623.7+ MB

#Check for dupliated values and delete them

In [10]:
nacc_copy = nacc_copy.drop_duplicates()

In [11]:
nacc_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201352 entries, 0 to 201351
Columns: 406 entries, NACCID to NPATGFR1
dtypes: float64(35), int64(370), object(1)
memory usage: 623.7+ MB

No duplicates in NACC data

# Keep only those participants who have visited the hospital at least twice.

In [12]:
# Count the occurrences of each NACCID in nacc_copy
naccid_counts = nacc_copy['NACCID'].value_counts()

# Identify NACCIDs that occur only once
naccids_to_remove = naccid_counts[naccid_counts == 1].index

# Remove rows from nacc_copy where NACCID is in the list of NACCIDs to remove
nacc_copy = nacc_copy[~nacc_copy['NACCID'].isin(naccids_to_remove)].copy()

# Display the info of the modified DataFrame to confirm the number of rows
print("Info of nacc_copy after removing single-visit NACCIDs:")
nacc_copy.info()

Info of nacc_copy after removing single-visit NACCIDs:
<class 'pandas.core.frame.DataFrame'>
Index: 184092 entries, 0 to 201350
Columns: 406 entries, NACCID to NPATGFR1
dtypes: float64(35), int64(370), object(1)
memory usage: 571.6+ MB

# Calculation of Age

birth month and year are already given. birth day is assumed to be 1st of the birth month.

In [13]:
# Convert date columns to datetime objects using only year and month for birth date
nacc_copy['birth_date'] = pd.to_datetime(nacc_copy['BIRTHYR'].astype(str) + '-' + nacc_copy['BIRTHMO'].astype(str), errors='coerce')
nacc_copy['visit_date'] = pd.to_datetime(nacc_copy['VISITYR'].astype(str) + '-' + nacc_copy['VISITMO'].astype(str) + '-' + nacc_copy['VISITDAY'].astype(str), errors='coerce')

# Calculate age
nacc_copy['Age'] = (nacc_copy['visit_date'] - nacc_copy['birth_date']).dt.days / 365.25

# # Format dates to 'day-month-year'
# nacc_copy['birth_date_formatted'] = nacc_copy['birth_date'].dt.strftime('%d-%m-%Y')
# nacc_copy['visit_date_formatted'] = nacc_copy['visit_date'].dt.strftime('%d-%m-%Y')


# Display the first few rows with the new 'Age' column and formatted dates
display(nacc_copy[['BIRTHYR', 'BIRTHMO', 'VISITYR', 'VISITMO', 'VISITDAY', 'Age']].head())

   BIRTHYR  BIRTHMO  VISITYR  VISITMO  VISITDAY        Age
0     1952        5     2022       12        28  70.658453
1     1952        5     2024        1        23  71.728953
4     1942        8     2022       11        14  80.287474
5     1942        8     2024        9         4  82.094456
7     1936        7     2022       11        15  86.373717

# Applying conditions based on NACCUDSD:

1. Extract only rows having NACCUDSD equal 3 or 4
2. Deleting the rows having NACCUDSD equal 4 and NACCALZD not equal to 1.
3. keeping the rows have NACCUDSD only 3 or converted from 3 to 4.

In [14]:
# Condition 1: Filter rows where NACCUDSD is either 3 or 4.
nacc_copy = nacc_copy[nacc_copy['NACCUDSD'].isin([3, 4])].copy()

# Condition 2: Remove rows where NACCUDSD is 4 and NACCALZD is not equal to 1.
nacc_copy = nacc_copy[~((nacc_copy['NACCUDSD'] == 4) & (nacc_copy['NACCALZD'] != 1))].copy()

# Condition 3: For rows where NACCUDSD is 4, check if there exists at least one other row with the same NACCID where NACCUDSD is 3.
# If no such row exists for that NACCID, delete the row with NACCUDSD equal to 4.

# Identify NACCIDs that have at least one row with NACCUDSD == 3
naccid_with_naccudsd_3 = nacc_copy[nacc_copy['NACCUDSD'] == 3]['NACCID'].unique()

# Create a condition for rows to keep:
# Either NACCUDSD is 3 OR (NACCUDSD is 4 AND the NACCID is in the list of NACCIDs with NACCUDSD == 3)
condition_naccudsd_4_with_3 = (nacc_copy['NACCUDSD'] == 3) | \
                              ((nacc_copy['NACCUDSD'] == 4) & (nacc_copy['NACCID'].isin(naccid_with_naccudsd_3)))

nacc_copy = nacc_copy[condition_naccudsd_4_with_3].copy()

In [15]:
nacc_copy_2 = nacc_copy.copy()

print("Updated copies created:")
print(f"- nacc_copy_2: {len(nacc_copy_2.columns)} columns")

Updated copies created:
- nacc_copy_2: 409 columns

# creating new feature named "time (days)"

In [16]:
# Add a new column 'time (days)' to nacc_copy_2 and initialize with NaN
nacc_copy_2['time (days)'] = np.nan

# Convert 'visit_date' to datetime objects if not already
nacc_copy_2['visit_date'] = pd.to_datetime(nacc_copy_2['visit_date'])

# Iterate through each unique NACCID in nacc_copy_2
for naccid in nacc_copy_2['NACCID'].unique():
    # Get rows for the current NACCID and sort by visit_date
    nacc_rows = nacc_copy_2[nacc_copy_2['NACCID'] == naccid].sort_values(by='visit_date')

    # Find the first occurrence of NACCUDSD == 3
    first_udsd3_date = nacc_rows[nacc_rows['NACCUDSD'] == 3]['visit_date'].min()

    # Find the first occurrence of NACCUDSD == 4
    first_udsd4_date = nacc_rows[nacc_rows['NACCUDSD'] == 4]['visit_date'].min()

    # Find the last occurrence of NACCUDSD == 3
    last_udsd3_date = nacc_rows[nacc_rows['NACCUDSD'] == 3]['visit_date'].max()

    # Condition 1: NACCID has at least one row with NACCUDSD == 4
    if pd.notna(first_udsd4_date):
        # Calculate the difference between the first NACCUDSD == 4 and first NACCUDSD == 3 dates
        # Ensure first_udsd3_date is not NaN before calculating difference
        if pd.notna(first_udsd3_date):
            time_difference = abs((first_udsd4_date - first_udsd3_date).days)

            # Find the index of the first occurrence of this NACCID
            first_occurrence_index = nacc_copy_2[nacc_copy_2['NACCID'] == naccid].index[0]

            # Update the 'time (days)' column in the first occurrence row
            nacc_copy_2.loc[first_occurrence_index, 'time (days)'] = time_difference

    # Condition 2: NACCID has only NACCUDSD == 3 across all its rows
    elif pd.notna(first_udsd3_date):
        # Calculate the difference between the last and first NACCUDSD == 3 dates
        time_difference = abs((last_udsd3_date - first_udsd3_date).days)

        # Find the index of the first occurrence of this NACCID
        first_occurrence_index = nacc_copy_2[nacc_copy_2['NACCID'] == naccid].index[0]

        # Update the 'time (days)' column in the first occurrence row
        nacc_copy_2.loc[first_occurrence_index, 'time (days)'] = time_difference

# Display the first few rows of nacc_copy_2 with the new column
print("nacc_copy_2 with 'time (days)' column:")
display(nacc_copy_2.head())

# Display the info of nacc_copy_2 to check the new column
print("\nInfo of nacc_copy_2:")
nacc_copy_2.info()

# # Display the value counts of the 'time (days)' column to see how many values were filled
# print("\nValue counts for the 'time (days)' column:")
# display(nacc_copy_2['time (days)'].value_counts(dropna=False))

nacc_copy_2 with 'time (days)' column:

,NACCID,SEX,EDUC,NACCNE4S,NACCFAM,NACCGDS,DEP2YRS,NACCMMSE,CRAFTVRS,CRAFTDVR,...,NPARTAG,NPATGSEV,NPATGAMY,NPATGAM1,NPATGFRN,NPATGFR1,birth_date,visit_date,Age,time (days)
0,NACC002909,1,16,1.0,1,4,0,-4,18,10,...,-4,-4,-4,-4,-4,-4,1952-05-01,2022-12-28,70.658453,391.0
1,NACC002909,1,16,1.0,1,1,-4,-4,19,0,...,-4,-4,-4,-4,-4,-4,1952-05-01,2024-01-23,71.728953,NaN
44,NACC063570,1,14,0.0,0,4,0,-4,12,8,...,-4,-4,-4,-4,-4,-4,1940-01-01,2022-08-02,82.584531,756.0
45,NACC063570,1,14,0.0,0,2,-4,-4,8,7,...,-4,-4,-4,-4,-4,-4,1940-01-01,2023-08-09,83.603012,NaN
46,NACC063570,1,14,0.0,0,1,-4,-4,12,9,...,-4,-4,-4,-4,-4,-4,1940-01-01,2024-08-27,84.654346,NaN

Info of nacc_copy_2:
<class 'pandas.core.frame.DataFrame'>
Index: 42339 entries, 0 to 201350
Columns: 410 entries, NACCID to time (days)
dtypes: datetime64[ns](2), float64(37), int64(370), object(1)
memory usage: 133.8+ MB

# creating new column "event" based on NACCUDSD

In [17]:
# Initialize the 'event' column with 0
nacc_copy_2['event'] = 0

# Iterate through each unique NACCID
for naccid in nacc_copy_2['NACCID'].unique():
    # Get all rows for the current NACCID
    nacc_rows = nacc_copy_2[nacc_copy_2['NACCID'] == naccid]

    # Check if NACCUDSD changes from 3 to 4
    if (nacc_rows['NACCUDSD'] == 3).any() and (nacc_rows['NACCUDSD'] == 4).any():
        # If the condition is met, set 'event' to 1 for all rows of this NACCID
        nacc_copy_2.loc[nacc_rows.index, 'event'] = 1

# Display the first few rows with the new 'event' column
print("nacc_copy_2 with 'event' column:")
display(nacc_copy_2.head())

# Display the value counts for the 'event' column
print("\nValue counts for the 'event' column:")
display(nacc_copy_2['event'].value_counts())

nacc_copy_2 with 'event' column:

,NACCID,SEX,EDUC,NACCNE4S,NACCFAM,NACCGDS,DEP2YRS,NACCMMSE,CRAFTVRS,CRAFTDVR,...,NPATGSEV,NPATGAMY,NPATGAM1,NPATGFRN,NPATGFR1,birth_date,visit_date,Age,time (days),event
0,NACC002909,1,16,1.0,1,4,0,-4,18,10,...,-4,-4,-4,-4,-4,1952-05-01,2022-12-28,70.658453,391.0,0
1,NACC002909,1,16,1.0,1,1,-4,-4,19,0,...,-4,-4,-4,-4,-4,1952-05-01,2024-01-23,71.728953,NaN,0
44,NACC063570,1,14,0.0,0,4,0,-4,12,8,...,-4,-4,-4,-4,-4,1940-01-01,2022-08-02,82.584531,756.0,0
45,NACC063570,1,14,0.0,0,2,-4,-4,8,7,...,-4,-4,-4,-4,-4,1940-01-01,2023-08-09,83.603012,NaN,0
46,NACC063570,1,14,0.0,0,1,-4,-4,12,9,...,-4,-4,-4,-4,-4,1940-01-01,2024-08-27,84.654346,NaN,0

Value counts for the 'event' column:

event
0    21910
1    20429
Name: count, dtype: int64

# Keep only unique rows in nacc_copy_2

In [18]:
# Drop duplicate NACCID values, keeping the first occurrence
nacc_copy_2 = nacc_copy_2.drop_duplicates(subset=['NACCID'], keep='first').copy()

# Display the info of the modified DataFrame to confirm the number of rows
print("Info of nacc_copy_2 after removing duplicate NACCIDs:")
nacc_copy_2.info()

# Display the first few rows to check the 'time (days)' column
print("\nFirst few rows of nacc_copy_2 after removing duplicate NACCIDs:")
display(nacc_copy_2.head())

Info of nacc_copy_2 after removing duplicate NACCIDs:
<class 'pandas.core.frame.DataFrame'>
Index: 12685 entries, 0 to 201348
Columns: 411 entries, NACCID to event
dtypes: datetime64[ns](2), float64(37), int64(371), object(1)
memory usage: 39.9+ MB

First few rows of nacc_copy_2 after removing duplicate NACCIDs:

,NACCID,SEX,EDUC,NACCNE4S,NACCFAM,NACCGDS,DEP2YRS,NACCMMSE,CRAFTVRS,CRAFTDVR,...,NPATGSEV,NPATGAMY,NPATGAM1,NPATGFRN,NPATGFR1,birth_date,visit_date,Age,time (days),event
0,NACC002909,1,16,1.0,1,4,0,-4,18,10,...,-4,-4,-4,-4,-4,1952-05-01,2022-12-28,70.658453,391.0,0
44,NACC063570,1,14,0.0,0,4,0,-4,12,8,...,-4,-4,-4,-4,-4,1940-01-01,2022-08-02,82.584531,756.0,0
51,NACC069522,2,14,1.0,1,2,0,-4,7,1,...,-4,-4,-4,-4,-4,1930-05-01,2022-09-22,92.394251,389.0,1
62,NACC086622,2,16,2.0,1,0,0,-4,4,0,...,-4,-4,-4,-4,-4,1950-07-01,2022-03-28,71.739904,756.0,1
64,NACC086775,2,14,0.0,0,1,0,-4,17,11,...,-4,-4,-4,-4,-4,1939-09-01,2022-05-13,82.696783,860.0,0

In [19]:
nacc_copy_2.head()

,NACCID,SEX,EDUC,NACCNE4S,NACCFAM,NACCGDS,DEP2YRS,NACCMMSE,CRAFTVRS,CRAFTDVR,...,NPATGSEV,NPATGAMY,NPATGAM1,NPATGFRN,NPATGFR1,birth_date,visit_date,Age,time (days),event
0,NACC002909,1,16,1.0,1,4,0,-4,18,10,...,-4,-4,-4,-4,-4,1952-05-01,2022-12-28,70.658453,391.0,0
44,NACC063570,1,14,0.0,0,4,0,-4,12,8,...,-4,-4,-4,-4,-4,1940-01-01,2022-08-02,82.584531,756.0,0
51,NACC069522,2,14,1.0,1,2,0,-4,7,1,...,-4,-4,-4,-4,-4,1930-05-01,2022-09-22,92.394251,389.0,1
62,NACC086622,2,16,2.0,1,0,0,-4,4,0,...,-4,-4,-4,-4,-4,1950-07-01,2022-03-28,71.739904,756.0,1
64,NACC086775,2,14,0.0,0,1,0,-4,17,11,...,-4,-4,-4,-4,-4,1939-09-01,2022-05-13,82.696783,860.0,0

In [20]:
nacc_copy_2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12685 entries, 0 to 201348
Columns: 411 entries, NACCID to event
dtypes: datetime64[ns](2), float64(37), int64(371), object(1)
memory usage: 39.9+ MB

# Check for missing values

In [21]:
nacc_copy_2.isnull().sum()

NACCID          0
SEX             0
EDUC            0
NACCNE4S       75
NACCFAM         0
               ..
birth_date      0
visit_date      0
Age             0
time (days)     0
event           0
Length: 411, dtype: int64

In [22]:
nacc_missing_count = nacc_copy_2.isnull().sum()
nacc_missing_percentage = (nacc_missing_count / len(nacc_copy_2)) * 100

print("Missing values in nacc_copy_2:")
display(pd.DataFrame({
    'Missing Count': nacc_missing_count,
    'Missing Percentage': nacc_missing_percentage
}))

Missing values in nacc_copy_2:

             Missing Count  Missing Percentage
NACCID                   0             0.00000
SEX                      0             0.00000
EDUC                     0             0.00000
NACCNE4S                75             0.59125
NACCFAM                  0             0.00000
...                    ...                 ...
birth_date               0             0.00000
visit_date               0             0.00000
Age                      0             0.00000
time (days)              0             0.00000
event                    0             0.00000

[411 rows x 2 columns]

# Drop null values

In [24]:
# Identify the NACCIDs that have missing values in 'NACCNE4S' in nacc_copy_2
naccids_to_drop = nacc_copy_2[nacc_copy_2['NACCNE4S'].isnull()]['NACCID']

# Drop rows with missing values in nacc_copy_2 based on 'NACCNE4S'
nacc_copy_2.dropna(subset=['NACCNE4S'], inplace=True)

# Verify that there are no more missing values in nacc_copy_2
print("Missing values in nacc_copy_2 after dropping rows:")
display(nacc_copy_2.isnull().sum())

Missing values in nacc_copy_2 after dropping rows:

NACCID         0
SEX            0
EDUC           0
NACCNE4S       0
NACCFAM        0
              ..
birth_date     0
visit_date     0
Age            0
time (days)    0
event          0
Length: 411, dtype: int64

In [25]:
nacc_copy_2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12610 entries, 0 to 201348
Columns: 411 entries, NACCID to event
dtypes: datetime64[ns](2), float64(37), int64(371), object(1)
memory usage: 39.6+ MB

# if the participants are not follwed-up till 3 years and didn't convert to AD,  we need to exclude them from the dataset to avoid introducing bias.

In [26]:
# Condition: 'event' is 0 and 'time (days)' is less than 1000
condition_to_remove = (nacc_copy_2['event'] == 0) & (nacc_copy_2['time (days)'] < 1000)

# Remove rows that meet the condition
nacc_copy_2 = nacc_copy_2[~condition_to_remove].copy()

# Display the info of the modified DataFrame to confirm the number of rows
print("Info of nacc_copy_2 after filtering:")
nacc_copy_2.info()

# Display the first few rows of the modified DataFrame
print("\nFirst few rows of nacc_copy_2 after filtering:")
display(nacc_copy_2.head())

Info of nacc_copy_2 after filtering:
<class 'pandas.core.frame.DataFrame'>
Index: 6690 entries, 51 to 201348
Columns: 411 entries, NACCID to event
dtypes: datetime64[ns](2), float64(37), int64(371), object(1)
memory usage: 21.0+ MB

First few rows of nacc_copy_2 after filtering:

,NACCID,SEX,EDUC,NACCNE4S,NACCFAM,NACCGDS,DEP2YRS,NACCMMSE,CRAFTVRS,CRAFTDVR,...,NPATGSEV,NPATGAMY,NPATGAM1,NPATGFRN,NPATGFR1,birth_date,visit_date,Age,time (days),event
51,NACC069522,2,14,1.0,1,2,0,-4,7,1,...,-4,-4,-4,-4,-4,1930-05-01,2022-09-22,92.394251,389.0,1
62,NACC086622,2,16,2.0,1,0,0,-4,4,0,...,-4,-4,-4,-4,-4,1950-07-01,2022-03-28,71.739904,756.0,1
104,NACC126237,1,14,1.0,9,2,0,-4,8,0,...,-4,-4,-4,-4,-4,1936-07-01,2022-08-15,86.121834,582.0,1
170,NACC174929,2,12,0.0,1,1,0,-4,16,2,...,-4,-4,-4,-4,-4,1936-09-01,2022-08-15,85.952088,582.0,1
194,NACC188799,2,14,9.0,1,0,0,-4,4,0,...,-4,-4,-4,-4,-4,1943-10-01,2022-02-07,78.354552,743.0,1

In [27]:
nacc_copy_2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6690 entries, 51 to 201348
Columns: 411 entries, NACCID to event
dtypes: datetime64[ns](2), float64(37), int64(371), object(1)
memory usage: 21.0+ MB

# Create new feature named - "event (1000 days)": target column for our project

In [28]:
# Create the new column 'event (1000 days)'
nacc_copy_2['event (1000 days)'] = 0  # Initialize with 0

# Apply the conditions
nacc_copy_2.loc[(nacc_copy_2['event'] == 1) & (nacc_copy_2['time (days)'] <= 1000), 'event (1000 days)'] = 1

# Display the first few rows with the new column
print("nacc_copy_2 with 'event (1000 days)' column:")
display(nacc_copy_2.head())

# Display the value counts for the new column
print("\nValue counts for the 'event (1000 days)' column:")
display(nacc_copy_2['event (1000 days)'].value_counts())

nacc_copy_2 with 'event (1000 days)' column:

,NACCID,SEX,EDUC,NACCNE4S,NACCFAM,NACCGDS,DEP2YRS,NACCMMSE,CRAFTVRS,CRAFTDVR,...,NPATGAMY,NPATGAM1,NPATGFRN,NPATGFR1,birth_date,visit_date,Age,time (days),event,event (1000 days)
51,NACC069522,2,14,1.0,1,2,0,-4,7,1,...,-4,-4,-4,-4,1930-05-01,2022-09-22,92.394251,389.0,1,1
62,NACC086622,2,16,2.0,1,0,0,-4,4,0,...,-4,-4,-4,-4,1950-07-01,2022-03-28,71.739904,756.0,1,1
104,NACC126237,1,14,1.0,9,2,0,-4,8,0,...,-4,-4,-4,-4,1936-07-01,2022-08-15,86.121834,582.0,1,1
170,NACC174929,2,12,0.0,1,1,0,-4,16,2,...,-4,-4,-4,-4,1936-09-01,2022-08-15,85.952088,582.0,1,1
194,NACC188799,2,14,9.0,1,0,0,-4,4,0,...,-4,-4,-4,-4,1943-10-01,2022-02-07,78.354552,743.0,1,1

Value counts for the 'event (1000 days)' column:

event (1000 days)
0    4161
1    2529
Name: count, dtype: int64

In [29]:
nacc_copy_2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6690 entries, 51 to 201348
Columns: 412 entries, NACCID to event (1000 days)
dtypes: datetime64[ns](2), float64(37), int64(372), object(1)
memory usage: 21.1+ MB

In [30]:
nacc_copy_2 = nacc_copy_2.drop(columns=['visit_date', 'birth_date', 'NACCUDSD', 'NACCALZD', 'event', 'NACCID', 'time (days)', 'NACCGDS', 'VISITDAY', 'VISITMO', 'VISITYR', 'BIRTHMO', 'BIRTHYR' ,'VISITDAY', 'VISITMO', 'VISITYR', 'BIRTHMO', 'BIRTHYR'], axis=1)

In [31]:
nacc_copy_2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6690 entries, 51 to 201348
Columns: 399 entries, SEX to event (1000 days)
dtypes: float64(36), int64(363)
memory usage: 20.4 MB

In [32]:
# Download the DataFrame as a CSV file
nacc_copy_2.to_csv("final_cleaned_data.csv", index=False)